# generating data to use for our tests
test_data <- testdata(nvar = 6, rper = 1, npoints = 100, noisevar = 1, linkfunc = identity,
                      dist = 'Gaussian', -10, 10)
true_val <- test_data[[2]]

# from this test, we see that our genetic algorithm will converge to the true value as generated by the data
# note: our algorithm passes the test with lm passed as the regression type, but gives many warnings, so it overloads the console trying to print them
test_that("select works", {

  result <- select(test_data[[1]], glm, Y ~ X1 + X2 + X3 + X4 + X5 + X6)
  result_val <- result[[1]]

  # here, we test for BIC as the fitness function
  result2 <- select(test_data[[1]], glm, Y ~ X1 + X2 + X3 + X4 + X5 + X6, fun = BIC)
  result2_val <- result2[[1]]

  expect_equal(result_val, true_val)
  expect_equal(result2_val, true_val)
})

# testing that our input checks put in place work
test_that("select errors", {
  expect_error(select(test_data[[1]], 1, Y ~ X1 + X2 + X3 + X4 + X5 + X6),
               "Error: The regression function needs to be a closure.")
  expect_error(select(test_data[[1]], lm, 1),
               "Error: The reg_fun input is not a valid formula.")
  expect_error(select(test_data[[1]], lm, Y ~ X1, fun = 'a'),
               "Error: The fitness function needs to be a closure.")
  expect_error(select(test_data[[1]], lm, Y ~ X1, ngen = 0.4),
               "Error: The generation number has to be a whole value.")
  expect_error(select(test_data[[1]], lm, Y ~ X1, sel = 'a'),
               "Error: The selection function needs to be a closure.")
  expect_error(select(test_data[[1]], lm, Y ~ X1, cross = 'b'),
               "Error: The crossover function needs to be a closure.")
  expect_error(select(test_data[[1]], lm, Y ~ X1, mut = 'c'),
               "Error: The mutation function needs to be a closure.")
})
